name: "xUnit.net CI Build (main)"
on:
  push:
    branches:
      - main
      - 'rel/**'
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: windows-2022
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Clone source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Install .NET SDK
        run: |
          pwsh -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command & '.\.github\workflows\dotnet-install.ps1 --channel 8.0'
          pwsh -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command & '.\.github\workflows\dotnet-install.ps1 --channel 6.0 --runtime dotnet'
          pwsh -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command & '.\.github\workflows\dotnet-install.ps1 --architecture x86 --channel 8.0'
          pwsh -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command & '.\.github\workflows\dotnet-install.ps1 --architecture x86 --channel 6.0 --runtime dotnet'

      - name: Get .NET information
        run: dotnet --info

      - name: "Build target: BuildAll & PublishPackages"
        env:
          PUSH_APIKEY: ${{ secrets.PUSH_APIKEY }}
          PUSH_URI: ${{ secrets.PUSH_URI }}
          SIGN_APP_ID: ${{ secrets.SIGN_APP_ID }}
          SIGN_APP_SECRET: ${{ secrets.SIGN_APP_SECRET }}
          SIGN_CERT_NAME: ${{ secrets.SIGN_CERT_NAME }}
          SIGN_SUBSCRIPTION: ${{ secrets.SIGN_SUBSCRIPTION }}
          SIGN_TENANT: ${{ secrets.SIGN_TENANT }}
          SIGN_TIMESTAMP_URI: ${{ secrets.SIGN_TIMESTAMP_URI }}
          SIGN_VAULT_URI: ${{ secrets.SIGN_VAULT_URI }}
        run: dotnet run --project tools/builder --no-launch-profile -- BuildAll PublishPackages --timing --no-x86

      - name: "Upload artifact: test"
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: artifacts/test
          compression-level: 9
        if: always()

      - name: "Upload artifact: packages"
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: artifacts/packages
          compression-level: 0
        if: always()
